name=input("enter your name:")
print(" welcome " + name)
age=input("enter your age:")
print("as your age is",age ,"you can give vote")
num1=int(input("enter the first number:"))
num2=int(input("enter the second number:"))
print(type(num1))
print(type(num2))
sum=int(num1+num2)
print(sum)